# Generated by Django 5.0.6 on 2024-06-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_post_comment_reservation_team_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
