# Generated by Django 5.0.6 on 2024-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
